### ISSUE TITLE
How to use this module from a terraform configuration?

### ISSUE THREAD

**Issue by Profpatsch** [tweag/terraform-nixos#13]
How to use this module from our terraform configuration?

The terraform docs have some [hints that you can import modules from external repos](https://www.terraform.io/docs/configuration/modules.html#module-versions), but they don’t provide any instructions for importing from git repositories as far as I can see.

cc @zimbatm

**Comment by Profpatsch** [comment]
A code snippet in the README that users can copy & paste into their config would be ideal.

**Comment by zimbatm** [comment]
do you mind extending the README?

The usage should look like this:

```tf
module "deploy_nixos" {
  source = "github.com/tweag/terraform-nixos//deploy_nixos"
}
```

if we had a release:

```tf
module "deploy_nixos" {
  source = "github.com/tweag/terraform-nixos//deploy_nixos?ref=v1.2.0"
}
```


doc: https://www.terraform.io/docs/modules/sources.html#github

**Comment by Profpatsch** [comment]
Awesome, I’ll submit a PR
