### ISSUE TITLE
deploy_nixos: ssh ControlPersist keeps connection open until timeout

### ISSUE THREAD

**Issue by Profpatsch** [tweag/terraform-nixos#20]
```
module.deploy_nixos.null_resource.deploy_nixos (local-exec): 103 store paths deleted, 226.86 MiB freed
module.deploy_nixos.null_resource.deploy_nixos (local-exec): debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
module.deploy_nixos.null_resource.deploy_nixos (local-exec): debug1: channel 2: free: client-session, nchannels 3
module.deploy_nixos.null_resource.deploy_nixos (local-exec): debug1: channel 1: free: mux-control, nchannels 2
module.deploy_nixos.null_resource.deploy_nixos: Still creating... [30s elapsed]
module.deploy_nixos.null_resource.deploy_nixos: Still creating... [40s elapsed]
module.deploy_nixos.null_resource.deploy_nixos: Still creating... [50s elapsed]
module.deploy_nixos.null_resource.deploy_nixos: Still creating... [1m0s elapsed]
module.deploy_nixos.null_resource.deploy_nixos: Still creating... [1m10s elapsed]
module.deploy_nixos.null_resource.deploy_nixos: Still creating... [1m20s elapsed]
```

The timeout is ~100s.

**Comment by zimbatm** [comment]
can you explain why this is a problem?

**Comment by Profpatsch** [comment]
Because it makes the `terraform apply` take 100 seconds more to finish.

**Comment by zimbatm** [comment]
Are you sure? ControlPersist starts a background process to manage the connection. It keeps the socket alive between ssh sessions to the same host.

**Comment by Profpatsch** [comment]
It might not be `ControlPersist` then, but it certainly has a timeout problem.

**Comment by betaboon** [comment]
Same happened to me.
as far as i understand the ssh-manpages the master-multiplex-connection is supposed to stay open for `ControlPersist` seconds even tho it has not being used.

i think the proper way to mitigate having to wait for this timeout to occur, the ControlMaster-connection should be closed gracefully when we don't require it anymore.
this can be achieved with `-O stop` 

i created a PR #29
