### ISSUE TITLE
Compare to tweag / terraform-provider-nixos ?

### ISSUE THREAD

**Issue by paulreimer** [tweag/terraform-nixos#30]
How does this repo (using terraform modules) compare to [this other tweag repo (implementing a terraform provider)](https://github.com/tweag/terraform-provider-nixos)? They look to have some overlap, but this repo seems more active + more recently maintained.

Is one or the other approach recommended, or would there be any reason to choose one over the other?

**Comment by zimbatm** [comment]
I recommend to use this project as it's better maintained. `terraform-provider-nixos` was our first attempt at tackling the integration between NixOS and Terraform and should probably be archived. /cc @grahamc

**Comment by grahamc** [comment]
+1 I'm on board.

**Comment by zimbatm** [comment]
Archived tweag/terraform-provider-nixos
