### ISSUE TITLE
Transfer request to nix-community

### ISSUE THREAD

**Issue by zimbatm** [tweag/terraform-nixos#64]
**Is your feature request related to a problem? Please describe.**
This project is mature now and could benefit from shared maintenance. I'm also doing most of the maintenance right now but am not associated with Tweag anymore.

**Describe the solution you'd like**
Move the repo to https://github.com/nix-community

**Describe alternatives you've considered**
Stop maintaining the project, or fork it.

**Additional context**
/cc @aspiwack

**Comment by Profpatsch** [comment]
Would love to see it in nix-community.

**Comment by luishfonseca** [comment]
Would like to see this in nix-community

**Comment by zimbatm** [comment]
I started maintaining a few forks of individual modules:
* https://github.com/numtide/terraform-nixos-amis 
* https://github.com/numtide/terraform-deploy-nixos-flakes

**Comment by aspiwack** [comment]
Hi @zimbatm .

First: an apology. The delay is entirely on me. I'm very sorry about it (you send your request as I was going on holiday, but honestly, this is no excuse for several months of delay).

On the main subject: I'd rather Tweag keeps the maintainership of this project, so I'm not inclined to transfer it out of the Tweag organisation. On the other hand, I just realised the heart of the problem: you don't have write access to this repository anymore. I'm giving you maintainer access immediately. You should have had access since you left (in fact I though you did)

**Comment by zimbatm** [comment]
No worries, there is nothing urgent.

If Tweag wants to maintain the project that's fine by me. I'm not going to spend more time on the project, but feel free to integrate the changes from my forks.

Some recommendations:
* Split the "flake" deploy module out of the "classic" one to reduce the bash script complexity. It's getting quite hairy.
* Automate AMI and other images inventory updates through GitHub actions so they are always fresh.

**Comment by dpc** [comment]
Hi! I've just discovered this project and it looks really cool. I'd like to give it a spin, but don't want to lock our infra to possibly unmaintained project.

After seeing last commit almost 2 years ago, multiple decent PRs without response, #69 and this issue I'm a bit reluctant, even though it is very tempting. 

If there was a higher chance it will get ongoing maintenance, then I would probably give it a try and down the line even contributed some fixes and help. No promises, but out of own self-interest it would make sense.

I realize the realities of Open Source project maintenance (time, why there's never enough time!) and also understand wanting to retain some control over owns creation. But it is clear that this project doesn't get enough attention recently, while multiple people are interested in using it. Seems to me that it would be better if it was was under nix-community umbrella, if the current maintainers can't find necessary time ATM. While I do recognize Tweag as a reputable and respectable Nix company there's only so many hours in a day. `nix-community` is a great and trustworthy place where I source my Nix tooling already and I could trust. 

Maintaining my own fork is meh (I'm myself also short on time maintaining stuff :D), and using forks of some other individuals is not appealing.

**Comment by thufschmitt** [comment]
Thanks for the nudge @dpc. Since we've evidently done a fairly bad job at maintaining this I think it's fair to transfer it to nix-community if someone is ready to take over on it.

@zimbatm are you willing to start maintaining this repository again if it goes out of the Tweag organization? Or is anyone else willing to take ownership?

**Comment by adrian-gierakowski** [comment]
I’d be happy to (co-)maintain it as I used the module in production in the past, and planning to use it again soon.

**Comment by zimbatm** [comment]
Sure. If it was moved to the nix-community, I would consider also consolidating https://github.com/numtide/terraform-upload-ami
https://github.com/numtide/terraform-nix-build
https://github.com/numtide/terraform-nixos-amis
https://github.com/numtide/terraform-deploy-nixos-flakes

**Comment by thufschmitt** [comment]
Great!

I'll do the transfer as soon as I get admin access to the repo then (unless you already have enough access @zimbatm, in which case feel free to directly do it yourself)

**Comment by thufschmitt** [comment]
Just asked GitHub to do the transfer. If my understanding is correct, this should just be waiting on approval from a `nix-community` admin

**Comment by zimbatm** [comment]
I invited you both to the org. @thufschmitt this will permit you to move the repo.

**Comment by thufschmitt** [comment]
Here we go!

![image](https://user-images.githubusercontent.com/7226587/216016629-a24eb54a-a46f-4dc0-bfb0-2d24bee35b61.png)

**Comment by zimbatm** [comment]
thanks, @adrian-gierakowski you are now officially the maintainer.

**Comment by adrian-gierakowski** [comment]
thanks @zimbatm!
